### PR TITLE
Bump image version to 0.23

### PR DESCRIPTION
**Pull request by MrKraboom**

### CODE REVIEW

**Review by TheWaWaR — APPROVED** [review]

**Review by TheWaWaR — CHANGES_REQUESTED** [review]
In order to apply the newly pushed `clippy` fix to let CI pass, please rebase the PR.

**Comment by MrKraboom** [comment]
Rebase is done :)

**Comment by TheWaWaR** [comment]
I already checked the change locally, I'm just going to merge it.

**Comment by TheWaWaR** [comment]
Thanks!

**Comment by MrKraboom** [comment]
You're welcome!

**Comment by TheWaWaR** [comment]
New version published.
https://crates.io/crates/escposify/0.4.0

**Pull request merged**
